export const QURAN_RECITERS: Array<{ id: string; label: string }> = [
  { id: "Alafasy_128kbps", label: "مشاري العفاسي" },
  { id: "Abdul_Basit_Murattal_192kbps", label: "عبد الباسط المرتل" },
  { id: "Hudhaify_128kbps", label: "عبدالرحمن الحذيفي" },
  { id: "Minshawy_Murattal_128kbps", label: "محمد المنشاوي" },
  { id: "Abdullah_Basfar_192kbps", label: "عبدالله بصفر" },
  { id: "Husary_128kbps", label: "محمود الحصري" },
  { id: "Abu_Bakr_Ash-Shaatree_128kbps", label: "أبو بكر الشاطري" },
  { id: "Nasser_Alqatami_128kbps", label: "ناصر القطامي" },
  { id: "Yasser_Ad-Dussary_128kbps", label: "ياسر الدوسري" },
  { id: "Maher_AlMuaiqly_64kbps", label: "ماهر المعيقلي" },
  { id: "Abdurrahmaan_As-Sudais_64kbps", label: "عبد الرحمن السديس" },
  { id: "Saood_ash-Shuraym_64kbps", label: "سعود الشريم" },
  { id: "Muhammad_Ayyoub_128kbps", label: "محمد أيوب" },
  { id: "Minshawy_Mujawwad_192kbps", label: "محمد المنشاوي المجود" },
  { id: "Muhammad_Jibreel_128kbps", label: "محمد جبريل" },
  { id: "Hani_Rifai_192kbps", label: "هاني الرفاعي" },
  { id: "Ghamadi_40kbps", label: "سعد الغامدي" },
  { id: "Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net", label: "أحمد العجمي" },
  { id: "AbdulSamad_64kbps", label: "عبد الباسط عبد الصمد" },
  { id: "Ibrahim_Akhdar_32kbps", label: "إبراهيم الأخضر" },
  // A1: Additional reciters
  { id: "Husary_Mujawwad_128kbps", label: "محمود الحصري (مجوّد)" },
  { id: "Abdul_Basit_Mujawwad_128kbps", label: "عبد الباسط (مجوّد)" },
  { id: "Maher_AlMuaiqly_128kbps", label: "ماهر المعيقلي (جودة عالية)" },
  { id: "Mohammad_al_Tablawi_128kbps", label: "محمد الطبلاوي" },
  { id: "Khalefa_Taniji_48kbps", label: "خليفة الطنيجي" },
  { id: "Sahl_Yasin_48kbps", label: "سهل ياسين" },
  { id: "Fares_Abbad_64kbps", label: "فارس عباد" },
];
